# Kitty Configuration - Dark & Crimson Theme

# --- Tipografía ---
font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        11.0

# --- Margen y Ventana ---
window_padding_width 12 16
background_opacity   0.94
confirm_os_window_close 0
enable_audio_bell    no

# --- Cursor ---
cursor               #ff787d
cursor_text_color    #111111
cursor_shape         beam
cursor_beam_thickness 1.8
cursor_blink_interval 0.5

# --- Selección y Enlaces ---
selection_background #e22b31
selection_foreground #ffffff
url_color            #ff787d
url_style            straight

# --- Barra de pestañas ---
tab_bar_style        powerline
active_tab_foreground   #ffffff
active_tab_background   #e22b31
inactive_tab_foreground #888888
inactive_tab_background #141417

# --- Paleta de Colores ---
background           #0a0a0d
foreground           #e4e4e7

# Black
color0               #18181b
color8               #3f3f46
# Red (Acentos del sistema)
color1               #e22b31
color9               #ff787d
# Green
color2               #4ade80
color10              #86efac
# Yellow
color3               #facc15
color11              #fde047
# Blue
color4               #60a5fa
color12              #93c5fd
# Magenta / Purple
color5               #c084fc
color13              #d8b4fe
# Cyan
color6               #22d3ee
color14              #67e8f9
# White
color7               #e4e4e7
color15              #ffffff
