"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = """
$python\
$conda\
$username\
[@](#f5f5f5 bold)\
$hostname\
[:](#646464)\
$directory\
$git_branch\
$git_status\
$cmd_duration\
$jobs\
$character"""

right_format = ""

[character]
success_symbol = "[\\$](#42a0bf bold)"
error_symbol = "[\\$](#42a0bf bold)"

[username]
show_always = true
format = "[$user](#f5f5f5 bold)"

[hostname]
ssh_only = false
format = "[$hostname](#f5f5f5 bold)"

[directory]
style = "bold #7fc4db"
truncate_to_repo = false
format = "[$path]($style) "

[git_branch]
style = "bold #7fc4db"
symbol = "git"
format = "[$symbol\\(]($style)[$branch](bold #a6e3a1)[\\)]($style) "

[git_status]
style = "bold #42a0bf"
conflicted = "x"
ahead = "^"
behind = "v"
diverged = "<>"
up_to_date = "="
untracked = "?"
stashed = "\\$"
modified = "!"
staged = "+"
renamed = ">"
deleted = "-"
format = "([$all_status$ahead_behind]($style)) "

[cmd_duration]
min_time = 2000
style = "bold #e2b714"
format = "[$duration]($style) "

[jobs]
symbol = "✦ "
style = "bold #7fc4db"
format = "[$symbol$number]($style) "

[status]
disabled = true

[python]
format = "([\\($virtualenv\\)](#a6e3a1 bold) )"
detect_extensions = []
detect_files = []
detect_folders = []
detect_env_vars = ["VIRTUAL_ENV"]

[conda]
format = "([\\($environment\\)](#a6e3a1 bold) )"
ignore_base = true


