"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = """
$username\
[@](#f5f5f5 bold)\
$hostname\
[:](#646464)\
$directory\
$git_branch\
$git_status\
$character"""

right_format = ""

[character]
success_symbol = "[\\$](#42a0bf bold)"
error_symbol = "[\\$](#42a0bf bold)"

[username]
show_always = true
format = "[$user](#f5f5f5 bold)"

[hostname]
ssh_only = false
format = "[$hostname](#f5f5f5 bold)"

[directory]
style = "bold #7fc4db"
truncate_to_repo = false
format = "[$path]($style) "

[git_branch]
style = "bold #7fc4db"
symbol = "git"
format = "[$symbol\\(]($style)[$branch](bold #a6e3a1)[\\)]($style) "

[git_status]
style = "bold #42a0bf"
conflicted = "x"
ahead = "^"
behind = "v"
diverged = "<>"
up_to_date = "="
untracked = "?"
stashed = "$"
modified = "!"
staged = "+"
renamed = ">"
deleted = "-"
format = "([$all_status$ahead_behind]($style))"
